### ISSUE TITLE
Вылетает в ошибку после Block 3... 

### ISSUE THREAD

**Issue by fedonkin** [VslTr/BinanceBot#4]
Такой интересный бот нашел, спасибо за него :) Но вот не задача... если на монете coin2 нету средств, то он естественно начинает подготовку к покупке и тут бац:
```
Traceback (most recent call last):
  File "E:/Crea/Trades/Active/VSLTR/Binbot.py", line 478, in <module>
    call_function = buycoin_counting() # Функция вернет кортеж из 3-х элементов
  File "E:/Crea/Trades/Active/VSLTR/Binbot.py", line 91, in buycoin_counting
    if t_history[0]["isBuyer"] == True:
IndexError: list index out of range
```

**Comment by fedonkin** [comment]
Решил:)
